name: Build and deploy Python project to Azure Function App - intervals-icu-ia

on:
  push:
    branches:
      - azure-serverless
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_130B1E89257249849BF2E2290E271DD8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3D1F4ACE3C6B4285A7769EB07F703A8C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37D25088C4784940A54D41992F381D94 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'intervals-icu-ia'
          slot-name: 'Production'
          package: '.'
